
networks:
  logistics-net:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:16-master
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=logistics_db
    volumes:
      - ./docker-data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - logistics-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M



  migrations:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./next-app:/app
    command: sh -c "npm install && npx sequelize-cli db:migrate"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/logistics_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logistics-net

  nextjs:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@postgres:5432/logistics_db
      - MAPBOX_ACCESS_TOKEN=<your_mapbox_access_token>
      - MAPBOX_DIRECTIONS_API=https://api.mapbox.com/directions/v5/mapbox/driving
      - MAPBOX_GEOCODING_API=https://api.mapbox.com/geocoding/v5/mapbox.places
    ports:
      - "3000:3000"
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - logistics-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M